//
// GetCorporationsCorporationIdDivisionsWalletWallet.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** wallet object */

public struct GetCorporationsCorporationIdDivisionsWalletWallet: Codable {

    /** division integer */
    public var division: Int?
    /** name string */
    public var name: String?

    public init(division: Int? = nil, name: String? = nil) {
        self.division = division
        self.name = name
    }


}
