//
// GetCharactersCharacterIdTitles200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCharactersCharacterIdTitles200Ok: Codable {

    /** name string */
    public var name: String?
    /** title_id integer */
    public var titleId: Int?

    public init(name: String? = nil, titleId: Int? = nil) {
        self.name = name
        self.titleId = titleId
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case titleId = "title_id"
    }

}
