//
// GetCharactersCharacterIdFwStatsVictoryPoints.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Summary of victory points gained by the given character for the enlisted faction */

public struct GetCharactersCharacterIdFwStatsVictoryPoints: Codable {

    /** Last week&#x27;s victory points gained by the given character */
    public var lastWeek: Int
    /** Total victory points gained since the given character enlisted */
    public var total: Int
    /** Yesterday&#x27;s victory points gained by the given character */
    public var yesterday: Int

    public init(lastWeek: Int, total: Int, yesterday: Int) {
        self.lastWeek = lastWeek
        self.total = total
        self.yesterday = yesterday
    }

    public enum CodingKeys: String, CodingKey { 
        case lastWeek = "last_week"
        case total
        case yesterday
    }

}
