//
// GetCorporationsCorporationIdIconsOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCorporationsCorporationIdIconsOk: Codable {

    /** px128x128 string */
    public var px128x128: String?
    /** px256x256 string */
    public var px256x256: String?
    /** px64x64 string */
    public var px64x64: String?

    public init(px128x128: String? = nil, px256x256: String? = nil, px64x64: String? = nil) {
        self.px128x128 = px128x128
        self.px256x256 = px256x256
        self.px64x64 = px64x64
    }


}
