//
// GetCharactersCharacterIdPlanetsPlanetIdRoute.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** route object */

public struct GetCharactersCharacterIdPlanetsPlanetIdRoute: Codable {

    /** content_type_id integer */
    public var contentTypeId: Int
    /** destination_pin_id integer */
    public var destinationPinId: Int64
    /** quantity number */
    public var quantity: Float
    /** route_id integer */
    public var routeId: Int64
    /** source_pin_id integer */
    public var sourcePinId: Int64
    /** list of pin ID waypoints */
    public var waypoints: [Int64]?

    public init(contentTypeId: Int, destinationPinId: Int64, quantity: Float, routeId: Int64, sourcePinId: Int64, waypoints: [Int64]? = nil) {
        self.contentTypeId = contentTypeId
        self.destinationPinId = destinationPinId
        self.quantity = quantity
        self.routeId = routeId
        self.sourcePinId = sourcePinId
        self.waypoints = waypoints
    }

    public enum CodingKeys: String, CodingKey { 
        case contentTypeId = "content_type_id"
        case destinationPinId = "destination_pin_id"
        case quantity
        case routeId = "route_id"
        case sourcePinId = "source_pin_id"
        case waypoints
    }

}
