//
// GetCharactersCharacterIdOpportunities200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCharactersCharacterIdOpportunities200Ok: Codable {

    /** completed_at string */
    public var completedAt: Date
    /** task_id integer */
    public var taskId: Int

    public init(completedAt: Date, taskId: Int) {
        self.completedAt = completedAt
        self.taskId = taskId
    }

    public enum CodingKeys: String, CodingKey { 
        case completedAt = "completed_at"
        case taskId = "task_id"
    }

}
