//
// GetContractsPublicItemsContractId200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetContractsPublicItemsContractId200Ok: Codable {

    /** is_blueprint_copy boolean */
    public var isBlueprintCopy: Bool?
    /** true if the contract issuer has submitted this item with the contract, false if the isser is asking for this item in the contract */
    public var isIncluded: Bool
    /** Unique ID for the item being sold. Not present if item is being requested by contract rather than sold with contract */
    public var itemId: Int64?
    /** Material Efficiency Level of the blueprint */
    public var materialEfficiency: Int?
    /** Number of items in the stack */
    public var quantity: Int
    /** Unique ID for the item, used by the contract system */
    public var recordId: Int64
    /** Number of runs remaining if the blueprint is a copy, -1 if it is an original */
    public var runs: Int?
    /** Time Efficiency Level of the blueprint */
    public var timeEfficiency: Int?
    /** Type ID for item */
    public var typeId: Int

    public init(isBlueprintCopy: Bool? = nil, isIncluded: Bool, itemId: Int64? = nil, materialEfficiency: Int? = nil, quantity: Int, recordId: Int64, runs: Int? = nil, timeEfficiency: Int? = nil, typeId: Int) {
        self.isBlueprintCopy = isBlueprintCopy
        self.isIncluded = isIncluded
        self.itemId = itemId
        self.materialEfficiency = materialEfficiency
        self.quantity = quantity
        self.recordId = recordId
        self.runs = runs
        self.timeEfficiency = timeEfficiency
        self.typeId = typeId
    }

    public enum CodingKeys: String, CodingKey { 
        case isBlueprintCopy = "is_blueprint_copy"
        case isIncluded = "is_included"
        case itemId = "item_id"
        case materialEfficiency = "material_efficiency"
        case quantity
        case recordId = "record_id"
        case runs
        case timeEfficiency = "time_efficiency"
        case typeId = "type_id"
    }

}
