//
// GetCharactersCharacterIdOnlineOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCharactersCharacterIdOnlineOk: Codable {

    /** Timestamp of the last login */
    public var lastLogin: Date?
    /** Timestamp of the last logout */
    public var lastLogout: Date?
    /** Total number of times the character has logged in */
    public var logins: Int?
    /** If the character is online */
    public var online: Bool

    public init(lastLogin: Date? = nil, lastLogout: Date? = nil, logins: Int? = nil, online: Bool) {
        self.lastLogin = lastLogin
        self.lastLogout = lastLogout
        self.logins = logins
        self.online = online
    }

    public enum CodingKeys: String, CodingKey { 
        case lastLogin = "last_login"
        case lastLogout = "last_logout"
        case logins
        case online
    }

}
