//
// GetCharactersCharacterIdCalendarEventIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Full details of a specific event */

public struct GetCharactersCharacterIdCalendarEventIdOk: Codable {

    public enum OwnerType: String, Codable { 
        case eveServer = "eve_server"
        case corporation = "corporation"
        case faction = "faction"
        case character = "character"
        case alliance = "alliance"
    }
    /** date string */
    public var date: Date
    /** Length in minutes */
    public var duration: Int
    /** event_id integer */
    public var eventId: Int
    /** importance integer */
    public var importance: Int
    /** owner_id integer */
    public var ownerId: Int
    /** owner_name string */
    public var ownerName: String
    /** owner_type string */
    public var ownerType: OwnerType
    /** response string */
    public var response: String
    /** text string */
    public var text: String
    /** title string */
    public var title: String

    public init(date: Date, duration: Int, eventId: Int, importance: Int, ownerId: Int, ownerName: String, ownerType: OwnerType, response: String, text: String, title: String) {
        self.date = date
        self.duration = duration
        self.eventId = eventId
        self.importance = importance
        self.ownerId = ownerId
        self.ownerName = ownerName
        self.ownerType = ownerType
        self.response = response
        self.text = text
        self.title = title
    }

    public enum CodingKeys: String, CodingKey { 
        case date
        case duration
        case eventId = "event_id"
        case importance
        case ownerId = "owner_id"
        case ownerName = "owner_name"
        case ownerType = "owner_type"
        case response
        case text
        case title
    }

}
