//
// GetCorporationsCorporationIdMedals200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCorporationsCorporationIdMedals200Ok: Codable {

    /** created_at string */
    public var createdAt: Date
    /** ID of the character who created this medal */
    public var creatorId: Int
    /** description string */
    public var _description: String
    /** medal_id integer */
    public var medalId: Int
    /** title string */
    public var title: String

    public init(createdAt: Date, creatorId: Int, _description: String, medalId: Int, title: String) {
        self.createdAt = createdAt
        self.creatorId = creatorId
        self._description = _description
        self.medalId = medalId
        self.title = title
    }

    public enum CodingKeys: String, CodingKey { 
        case createdAt = "created_at"
        case creatorId = "creator_id"
        case _description = "description"
        case medalId = "medal_id"
        case title
    }

}
