//
// GetCharactersCharacterIdPlanetsPlanetIdPin.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** pin object */

public struct GetCharactersCharacterIdPlanetsPlanetIdPin: Codable {

    /** contents array */
    public var contents: [GetCharactersCharacterIdPlanetsPlanetIdContent]?
    /** expiry_time string */
    public var expiryTime: Date?
    public var extractorDetails: GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails?
    public var factoryDetails: GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails?
    /** install_time string */
    public var installTime: Date?
    /** last_cycle_start string */
    public var lastCycleStart: Date?
    /** latitude number */
    public var latitude: Float
    /** longitude number */
    public var longitude: Float
    /** pin_id integer */
    public var pinId: Int64
    /** schematic_id integer */
    public var schematicId: Int?
    /** type_id integer */
    public var typeId: Int

    public init(contents: [GetCharactersCharacterIdPlanetsPlanetIdContent]? = nil, expiryTime: Date? = nil, extractorDetails: GetCharactersCharacterIdPlanetsPlanetIdExtractorDetails? = nil, factoryDetails: GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails? = nil, installTime: Date? = nil, lastCycleStart: Date? = nil, latitude: Float, longitude: Float, pinId: Int64, schematicId: Int? = nil, typeId: Int) {
        self.contents = contents
        self.expiryTime = expiryTime
        self.extractorDetails = extractorDetails
        self.factoryDetails = factoryDetails
        self.installTime = installTime
        self.lastCycleStart = lastCycleStart
        self.latitude = latitude
        self.longitude = longitude
        self.pinId = pinId
        self.schematicId = schematicId
        self.typeId = typeId
    }

    public enum CodingKeys: String, CodingKey { 
        case contents
        case expiryTime = "expiry_time"
        case extractorDetails = "extractor_details"
        case factoryDetails = "factory_details"
        case installTime = "install_time"
        case lastCycleStart = "last_cycle_start"
        case latitude
        case longitude
        case pinId = "pin_id"
        case schematicId = "schematic_id"
        case typeId = "type_id"
    }

}
