//
// GetCorporationsCorporationIdAlliancehistory200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCorporationsCorporationIdAlliancehistory200Ok: Codable {

    /** alliance_id integer */
    public var allianceId: Int?
    /** True if the alliance has been closed */
    public var isDeleted: Bool?
    /** An incrementing ID that can be used to canonically establish order of records in cases where dates may be ambiguous */
    public var recordId: Int
    /** start_date string */
    public var startDate: Date

    public init(allianceId: Int? = nil, isDeleted: Bool? = nil, recordId: Int, startDate: Date) {
        self.allianceId = allianceId
        self.isDeleted = isDeleted
        self.recordId = recordId
        self.startDate = startDate
    }

    public enum CodingKeys: String, CodingKey { 
        case allianceId = "alliance_id"
        case isDeleted = "is_deleted"
        case recordId = "record_id"
        case startDate = "start_date"
    }

}
