//
// GetCorporationsCorporationIdMembertracking200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCorporationsCorporationIdMembertracking200Ok: Codable {

    /** base_id integer */
    public var baseId: Int?
    /** character_id integer */
    public var characterId: Int
    /** location_id integer */
    public var locationId: Int64?
    /** logoff_date string */
    public var logoffDate: Date?
    /** logon_date string */
    public var logonDate: Date?
    /** ship_type_id integer */
    public var shipTypeId: Int?
    /** start_date string */
    public var startDate: Date?

    public init(baseId: Int? = nil, characterId: Int, locationId: Int64? = nil, logoffDate: Date? = nil, logonDate: Date? = nil, shipTypeId: Int? = nil, startDate: Date? = nil) {
        self.baseId = baseId
        self.characterId = characterId
        self.locationId = locationId
        self.logoffDate = logoffDate
        self.logonDate = logonDate
        self.shipTypeId = shipTypeId
        self.startDate = startDate
    }

    public enum CodingKeys: String, CodingKey { 
        case baseId = "base_id"
        case characterId = "character_id"
        case locationId = "location_id"
        case logoffDate = "logoff_date"
        case logonDate = "logon_date"
        case shipTypeId = "ship_type_id"
        case startDate = "start_date"
    }

}
