//
// GetFwLeaderboardsOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetFwLeaderboardsOk: Codable {

    public var kills: GetFwLeaderboardsKills
    public var victoryPoints: GetFwLeaderboardsVictoryPoints

    public init(kills: GetFwLeaderboardsKills, victoryPoints: GetFwLeaderboardsVictoryPoints) {
        self.kills = kills
        self.victoryPoints = victoryPoints
    }

    public enum CodingKeys: String, CodingKey { 
        case kills
        case victoryPoints = "victory_points"
    }

}
