//
// GetFwWars200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetFwWars200Ok: Codable {

    /** The faction ID of the enemy faction. */
    public var againstId: Int
    /** faction_id integer */
    public var factionId: Int

    public init(againstId: Int, factionId: Int) {
        self.againstId = againstId
        self.factionId = factionId
    }

    public enum CodingKeys: String, CodingKey { 
        case againstId = "against_id"
        case factionId = "faction_id"
    }

}
