//
// GetIndustryFacilities200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetIndustryFacilities200Ok: Codable {

    /** ID of the facility */
    public var facilityId: Int64
    /** Owner of the facility */
    public var ownerId: Int
    /** Region ID where the facility is */
    public var regionId: Int
    /** Solar system ID where the facility is */
    public var solarSystemId: Int
    /** Tax imposed by the facility */
    public var tax: Float?
    /** Type ID of the facility */
    public var typeId: Int

    public init(facilityId: Int64, ownerId: Int, regionId: Int, solarSystemId: Int, tax: Float? = nil, typeId: Int) {
        self.facilityId = facilityId
        self.ownerId = ownerId
        self.regionId = regionId
        self.solarSystemId = solarSystemId
        self.tax = tax
        self.typeId = typeId
    }

    public enum CodingKeys: String, CodingKey { 
        case facilityId = "facility_id"
        case ownerId = "owner_id"
        case regionId = "region_id"
        case solarSystemId = "solar_system_id"
        case tax
        case typeId = "type_id"
    }

}
