//
// GetKillmailsKillmailIdKillmailHashOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetKillmailsKillmailIdKillmailHashOk: Codable {

    /** attackers array */
    public var attackers: [GetKillmailsKillmailIdKillmailHashAttacker]
    /** ID of the killmail */
    public var killmailId: Int
    /** Time that the victim was killed and the killmail generated  */
    public var killmailTime: Date
    /** Moon if the kill took place at one */
    public var moonId: Int?
    /** Solar system that the kill took place in  */
    public var solarSystemId: Int
    public var victim: GetKillmailsKillmailIdKillmailHashVictim
    /** War if the killmail is generated in relation to an official war  */
    public var warId: Int?

    public init(attackers: [GetKillmailsKillmailIdKillmailHashAttacker], killmailId: Int, killmailTime: Date, moonId: Int? = nil, solarSystemId: Int, victim: GetKillmailsKillmailIdKillmailHashVictim, warId: Int? = nil) {
        self.attackers = attackers
        self.killmailId = killmailId
        self.killmailTime = killmailTime
        self.moonId = moonId
        self.solarSystemId = solarSystemId
        self.victim = victim
        self.warId = warId
    }

    public enum CodingKeys: String, CodingKey { 
        case attackers
        case killmailId = "killmail_id"
        case killmailTime = "killmail_time"
        case moonId = "moon_id"
        case solarSystemId = "solar_system_id"
        case victim
        case warId = "war_id"
    }

}
