//
// GetMarketsRegionIdHistory200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetMarketsRegionIdHistory200Ok: Codable {

    /** average number */
    public var average: Double
    /** The date of this historical statistic entry */
    public var date: Date
    /** highest number */
    public var highest: Double
    /** lowest number */
    public var lowest: Double
    /** Total number of orders happened that day */
    public var orderCount: Int64
    /** Total */
    public var volume: Int64

    public init(average: Double, date: Date, highest: Double, lowest: Double, orderCount: Int64, volume: Int64) {
        self.average = average
        self.date = date
        self.highest = highest
        self.lowest = lowest
        self.orderCount = orderCount
        self.volume = volume
    }

    public enum CodingKeys: String, CodingKey { 
        case average
        case date
        case highest
        case lowest
        case orderCount = "order_count"
        case volume
    }

}
