//
// GetOpportunitiesGroupsGroupIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetOpportunitiesGroupsGroupIdOk: Codable {

    /** The groups that are connected to this group on the opportunities map */
    public var connectedGroups: [Int]
    /** description string */
    public var _description: String
    /** group_id integer */
    public var groupId: Int
    /** name string */
    public var name: String
    /** notification string */
    public var notification: String
    /** Tasks need to complete for this group */
    public var requiredTasks: [Int]

    public init(connectedGroups: [Int], _description: String, groupId: Int, name: String, notification: String, requiredTasks: [Int]) {
        self.connectedGroups = connectedGroups
        self._description = _description
        self.groupId = groupId
        self.name = name
        self.notification = notification
        self.requiredTasks = requiredTasks
    }

    public enum CodingKeys: String, CodingKey { 
        case connectedGroups = "connected_groups"
        case _description = "description"
        case groupId = "group_id"
        case name
        case notification
        case requiredTasks = "required_tasks"
    }

}
