//
// GetUniverseFactions200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetUniverseFactions200Ok: Codable {

    /** corporation_id integer */
    public var corporationId: Int?
    /** description string */
    public var _description: String
    /** faction_id integer */
    public var factionId: Int
    /** is_unique boolean */
    public var isUnique: Bool
    /** militia_corporation_id integer */
    public var militiaCorporationId: Int?
    /** name string */
    public var name: String
    /** size_factor number */
    public var sizeFactor: Float
    /** solar_system_id integer */
    public var solarSystemId: Int?
    /** station_count integer */
    public var stationCount: Int
    /** station_system_count integer */
    public var stationSystemCount: Int

    public init(corporationId: Int? = nil, _description: String, factionId: Int, isUnique: Bool, militiaCorporationId: Int? = nil, name: String, sizeFactor: Float, solarSystemId: Int? = nil, stationCount: Int, stationSystemCount: Int) {
        self.corporationId = corporationId
        self._description = _description
        self.factionId = factionId
        self.isUnique = isUnique
        self.militiaCorporationId = militiaCorporationId
        self.name = name
        self.sizeFactor = sizeFactor
        self.solarSystemId = solarSystemId
        self.stationCount = stationCount
        self.stationSystemCount = stationSystemCount
    }

    public enum CodingKeys: String, CodingKey { 
        case corporationId = "corporation_id"
        case _description = "description"
        case factionId = "faction_id"
        case isUnique = "is_unique"
        case militiaCorporationId = "militia_corporation_id"
        case name
        case sizeFactor = "size_factor"
        case solarSystemId = "solar_system_id"
        case stationCount = "station_count"
        case stationSystemCount = "station_system_count"
    }

}
