//
// InternalServerError.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Internal server error model */

public struct InternalServerError: Codable {

    /** Internal server error message */
    public var error: String

    public init(error: String) {
        self.error = error
    }


}
