//
// PostUniverseIdsOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct PostUniverseIdsOk: Codable {

    /** agents array */
    public var agents: [PostUniverseIdsAgent]?
    /** alliances array */
    public var alliances: [PostUniverseIdsAlliance]?
    /** characters array */
    public var characters: [PostUniverseIdsCharacter]?
    /** constellations array */
    public var constellations: [PostUniverseIdsConstellation]?
    /** corporations array */
    public var corporations: [PostUniverseIdsCorporation]?
    /** factions array */
    public var factions: [PostUniverseIdsFaction]?
    /** inventory_types array */
    public var inventoryTypes: [PostUniverseIdsInventoryType]?
    /** regions array */
    public var regions: [PostUniverseIdsRegion]?
    /** stations array */
    public var stations: [PostUniverseIdsStation]?
    /** systems array */
    public var systems: [PostUniverseIdsSystem]?

    public init(agents: [PostUniverseIdsAgent]? = nil, alliances: [PostUniverseIdsAlliance]? = nil, characters: [PostUniverseIdsCharacter]? = nil, constellations: [PostUniverseIdsConstellation]? = nil, corporations: [PostUniverseIdsCorporation]? = nil, factions: [PostUniverseIdsFaction]? = nil, inventoryTypes: [PostUniverseIdsInventoryType]? = nil, regions: [PostUniverseIdsRegion]? = nil, stations: [PostUniverseIdsStation]? = nil, systems: [PostUniverseIdsSystem]? = nil) {
        self.agents = agents
        self.alliances = alliances
        self.characters = characters
        self.constellations = constellations
        self.corporations = corporations
        self.factions = factions
        self.inventoryTypes = inventoryTypes
        self.regions = regions
        self.stations = stations
        self.systems = systems
    }

    public enum CodingKeys: String, CodingKey { 
        case agents
        case alliances
        case characters
        case constellations
        case corporations
        case factions
        case inventoryTypes = "inventory_types"
        case regions
        case stations
        case systems
    }

}
