//
// PutFleetsFleetIdNewSettings.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** new_settings object */

public struct PutFleetsFleetIdNewSettings: Codable {

    /** Should free-move be enabled in the fleet */
    public var isFreeMove: Bool?
    /** New fleet MOTD in CCP flavoured HTML */
    public var motd: String?

    public init(isFreeMove: Bool? = nil, motd: String? = nil) {
        self.isFreeMove = isFreeMove
        self.motd = motd
    }

    public enum CodingKeys: String, CodingKey { 
        case isFreeMove = "is_free_move"
        case motd
    }

}
