//
// PutFleetsFleetIdMembersMemberIdUnprocessableEntity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 422 unprocessable entity object */

public struct PutFleetsFleetIdMembersMemberIdUnprocessableEntity: Codable {

    /** error message */
    public var error: String?

    public init(error: String? = nil) {
        self.error = error
    }


}
