//
// GetCharactersCharacterIdAssetsNotFound.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Requested page does not exist */

public struct GetCharactersCharacterIdAssetsNotFound: Codable {

    /** error message */
    public var error: String?

    public init(error: String? = nil) {
        self.error = error
    }


}
