//
// GetContractsPublicRegionId200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetContractsPublicRegionId200Ok: Codable {

    public enum ModelType: String, Codable { 
        case unknown = "unknown"
        case itemExchange = "item_exchange"
        case auction = "auction"
        case courier = "courier"
        case loan = "loan"
    }
    /** Buyout price (for Auctions only) */
    public var buyout: Double?
    /** Collateral price (for Couriers only) */
    public var collateral: Double?
    /** contract_id integer */
    public var contractId: Int
    /** Expiration date of the contract */
    public var dateExpired: Date
    /** Сreation date of the contract */
    public var dateIssued: Date
    /** Number of days to perform the contract */
    public var daysToComplete: Int?
    /** End location ID (for Couriers contract) */
    public var endLocationId: Int64?
    /** true if the contract was issued on behalf of the issuer&#x27;s corporation */
    public var forCorporation: Bool?
    /** Character&#x27;s corporation ID for the issuer */
    public var issuerCorporationId: Int
    /** Character ID for the issuer */
    public var issuerId: Int
    /** Price of contract (for ItemsExchange and Auctions) */
    public var price: Double?
    /** Remuneration for contract (for Couriers only) */
    public var reward: Double?
    /** Start location ID (for Couriers contract) */
    public var startLocationId: Int64?
    /** Title of the contract */
    public var title: String?
    /** Type of the contract */
    public var type: ModelType
    /** Volume of items in the contract */
    public var volume: Double?

    public init(buyout: Double? = nil, collateral: Double? = nil, contractId: Int, dateExpired: Date, dateIssued: Date, daysToComplete: Int? = nil, endLocationId: Int64? = nil, forCorporation: Bool? = nil, issuerCorporationId: Int, issuerId: Int, price: Double? = nil, reward: Double? = nil, startLocationId: Int64? = nil, title: String? = nil, type: ModelType, volume: Double? = nil) {
        self.buyout = buyout
        self.collateral = collateral
        self.contractId = contractId
        self.dateExpired = dateExpired
        self.dateIssued = dateIssued
        self.daysToComplete = daysToComplete
        self.endLocationId = endLocationId
        self.forCorporation = forCorporation
        self.issuerCorporationId = issuerCorporationId
        self.issuerId = issuerId
        self.price = price
        self.reward = reward
        self.startLocationId = startLocationId
        self.title = title
        self.type = type
        self.volume = volume
    }

    public enum CodingKeys: String, CodingKey { 
        case buyout
        case collateral
        case contractId = "contract_id"
        case dateExpired = "date_expired"
        case dateIssued = "date_issued"
        case daysToComplete = "days_to_complete"
        case endLocationId = "end_location_id"
        case forCorporation = "for_corporation"
        case issuerCorporationId = "issuer_corporation_id"
        case issuerId = "issuer_id"
        case price
        case reward
        case startLocationId = "start_location_id"
        case title
        case type
        case volume
    }

}
