//
// GetCorporationsCorporationIdBookmarksFolders200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCorporationsCorporationIdBookmarksFolders200Ok: Codable {

    /** creator_id integer */
    public var creatorId: Int?
    /** folder_id integer */
    public var folderId: Int
    /** name string */
    public var name: String

    public init(creatorId: Int? = nil, folderId: Int, name: String) {
        self.creatorId = creatorId
        self.folderId = folderId
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case creatorId = "creator_id"
        case folderId = "folder_id"
        case name
    }

}
