//
// GetCharactersCharacterIdMailLabelsLabel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** label object */

public struct GetCharactersCharacterIdMailLabelsLabel: Codable {

    public enum Color: String, Codable { 
        case _0000fe = "#0000fe"
        case _006634 = "#006634"
        case _0099ff = "#0099ff"
        case _00ff33 = "#00ff33"
        case _01ffff = "#01ffff"
        case _349800 = "#349800"
        case _660066 = "#660066"
        case _666666 = "#666666"
        case _999999 = "#999999"
        case _99ffff = "#99ffff"
        case _9a0000 = "#9a0000"
        case ccff9a = "#ccff9a"
        case e6e6e6 = "#e6e6e6"
        case fe0000 = "#fe0000"
        case ff6600 = "#ff6600"
        case ffff01 = "#ffff01"
        case ffffcd = "#ffffcd"
        case ffffff = "#ffffff"
    }
    /** color string */
    public var color: Color?
    /** label_id integer */
    public var labelId: Int?
    /** name string */
    public var name: String?
    /** unread_count integer */
    public var unreadCount: Int?

    public init(color: Color? = nil, labelId: Int? = nil, name: String? = nil, unreadCount: Int? = nil) {
        self.color = color
        self.labelId = labelId
        self.name = name
        self.unreadCount = unreadCount
    }

    public enum CodingKeys: String, CodingKey { 
        case color
        case labelId = "label_id"
        case name
        case unreadCount = "unread_count"
    }

}
