//
// GetCharactersCharacterIdMailMailIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCharactersCharacterIdMailMailIdOk: Codable {

    /** Mail&#x27;s body */
    public var body: String?
    /** From whom the mail was sent */
    public var from: Int?
    /** Labels attached to the mail */
    public var labels: [Int]?
    /** Whether the mail is flagged as read */
    public var read: Bool?
    /** Recipients of the mail */
    public var recipients: [GetCharactersCharacterIdMailMailIdRecipient]?
    /** Mail subject */
    public var subject: String?
    /** When the mail was sent */
    public var timestamp: Date?

    public init(body: String? = nil, from: Int? = nil, labels: [Int]? = nil, read: Bool? = nil, recipients: [GetCharactersCharacterIdMailMailIdRecipient]? = nil, subject: String? = nil, timestamp: Date? = nil) {
        self.body = body
        self.from = from
        self.labels = labels
        self.read = read
        self.recipients = recipients
        self.subject = subject
        self.timestamp = timestamp
    }


}
