//
// GetCharactersCharacterIdSkillqueue200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCharactersCharacterIdSkillqueue200Ok: Codable {

    /** Date on which training of the skill will complete. Omitted if the skill queue is paused. */
    public var finishDate: Date?
    /** finished_level integer */
    public var finishedLevel: Int
    /** level_end_sp integer */
    public var levelEndSp: Int?
    /** Amount of SP that was in the skill when it started training it&#x27;s current level. Used to calculate % of current level complete. */
    public var levelStartSp: Int?
    /** queue_position integer */
    public var queuePosition: Int
    /** skill_id integer */
    public var skillId: Int
    /** start_date string */
    public var startDate: Date?
    /** training_start_sp integer */
    public var trainingStartSp: Int?

    public init(finishDate: Date? = nil, finishedLevel: Int, levelEndSp: Int? = nil, levelStartSp: Int? = nil, queuePosition: Int, skillId: Int, startDate: Date? = nil, trainingStartSp: Int? = nil) {
        self.finishDate = finishDate
        self.finishedLevel = finishedLevel
        self.levelEndSp = levelEndSp
        self.levelStartSp = levelStartSp
        self.queuePosition = queuePosition
        self.skillId = skillId
        self.startDate = startDate
        self.trainingStartSp = trainingStartSp
    }

    public enum CodingKeys: String, CodingKey { 
        case finishDate = "finish_date"
        case finishedLevel = "finished_level"
        case levelEndSp = "level_end_sp"
        case levelStartSp = "level_start_sp"
        case queuePosition = "queue_position"
        case skillId = "skill_id"
        case startDate = "start_date"
        case trainingStartSp = "training_start_sp"
    }

}
