//
// GetCorporationCorporationIdMiningObservers200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCorporationCorporationIdMiningObservers200Ok: Codable {

    public enum ObserverType: String, Codable { 
        case structure = "structure"
    }
    /** last_updated string */
    public var lastUpdated: Date
    /** The entity that was observing the asteroid field when it was mined.  */
    public var observerId: Int64
    /** The category of the observing entity */
    public var observerType: ObserverType

    public init(lastUpdated: Date, observerId: Int64, observerType: ObserverType) {
        self.lastUpdated = lastUpdated
        self.observerId = observerId
        self.observerType = observerType
    }

    public enum CodingKeys: String, CodingKey { 
        case lastUpdated = "last_updated"
        case observerId = "observer_id"
        case observerType = "observer_type"
    }

}
