//
// GetCharactersCharacterIdContractsContractIdItems200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCharactersCharacterIdContractsContractIdItems200Ok: Codable {

    /** true if the contract issuer has submitted this item with the contract, false if the isser is asking for this item in the contract */
    public var isIncluded: Bool
    /** is_singleton boolean */
    public var isSingleton: Bool
    /** Number of items in the stack */
    public var quantity: Int
    /** -1 indicates that the item is a singleton (non-stackable). If the item happens to be a Blueprint, -1 is an Original and -2 is a Blueprint Copy */
    public var rawQuantity: Int?
    /** Unique ID for the item */
    public var recordId: Int64
    /** Type ID for item */
    public var typeId: Int

    public init(isIncluded: Bool, isSingleton: Bool, quantity: Int, rawQuantity: Int? = nil, recordId: Int64, typeId: Int) {
        self.isIncluded = isIncluded
        self.isSingleton = isSingleton
        self.quantity = quantity
        self.rawQuantity = rawQuantity
        self.recordId = recordId
        self.typeId = typeId
    }

    public enum CodingKeys: String, CodingKey { 
        case isIncluded = "is_included"
        case isSingleton = "is_singleton"
        case quantity
        case rawQuantity = "raw_quantity"
        case recordId = "record_id"
        case typeId = "type_id"
    }

}
