//
// GetDogmaAttributesAttributeIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetDogmaAttributesAttributeIdOk: Codable {

    /** attribute_id integer */
    public var attributeId: Int
    /** default_value number */
    public var defaultValue: Float?
    /** description string */
    public var _description: String?
    /** display_name string */
    public var displayName: String?
    /** high_is_good boolean */
    public var highIsGood: Bool?
    /** icon_id integer */
    public var iconId: Int?
    /** name string */
    public var name: String?
    /** published boolean */
    public var published: Bool?
    /** stackable boolean */
    public var stackable: Bool?
    /** unit_id integer */
    public var unitId: Int?

    public init(attributeId: Int, defaultValue: Float? = nil, _description: String? = nil, displayName: String? = nil, highIsGood: Bool? = nil, iconId: Int? = nil, name: String? = nil, published: Bool? = nil, stackable: Bool? = nil, unitId: Int? = nil) {
        self.attributeId = attributeId
        self.defaultValue = defaultValue
        self._description = _description
        self.displayName = displayName
        self.highIsGood = highIsGood
        self.iconId = iconId
        self.name = name
        self.published = published
        self.stackable = stackable
        self.unitId = unitId
    }

    public enum CodingKeys: String, CodingKey { 
        case attributeId = "attribute_id"
        case defaultValue = "default_value"
        case _description = "description"
        case displayName = "display_name"
        case highIsGood = "high_is_good"
        case iconId = "icon_id"
        case name
        case published
        case stackable
        case unitId = "unit_id"
    }

}
