//
// GetFleetsFleetIdWingsSquad.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** squad object */

public struct GetFleetsFleetIdWingsSquad: Codable {

    /** id integer */
    public var _id: Int64
    /** name string */
    public var name: String

    public init(_id: Int64, name: String) {
        self._id = _id
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
    }

}
