//
// GetFwLeaderboardsCharactersKills.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Top 100 rankings of pilots by number of kills from yesterday, last week and in total */

public struct GetFwLeaderboardsCharactersKills: Codable {

    /** Top 100 ranking of pilots active in faction warfare by total kills. A pilot is considered \&quot;active\&quot; if they have participated in faction warfare in the past 14 days */
    public var activeTotal: [GetFwLeaderboardsCharactersActiveTotalActiveTotal]
    /** Top 100 ranking of pilots by kills in the past week */
    public var lastWeek: [GetFwLeaderboardsCharactersLastWeekLastWeek]
    /** Top 100 ranking of pilots by kills in the past day */
    public var yesterday: [GetFwLeaderboardsCharactersYesterdayYesterday]

    public init(activeTotal: [GetFwLeaderboardsCharactersActiveTotalActiveTotal], lastWeek: [GetFwLeaderboardsCharactersLastWeekLastWeek], yesterday: [GetFwLeaderboardsCharactersYesterdayYesterday]) {
        self.activeTotal = activeTotal
        self.lastWeek = lastWeek
        self.yesterday = yesterday
    }

    public enum CodingKeys: String, CodingKey { 
        case activeTotal = "active_total"
        case lastWeek = "last_week"
        case yesterday
    }

}
