//
// GetFwLeaderboardsCharactersActiveTotalActiveTotal1.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** active_total object */

public struct GetFwLeaderboardsCharactersActiveTotalActiveTotal1: Codable {

    /** Amount of victory points */
    public var amount: Int?
    /** character_id integer */
    public var characterId: Int?

    public init(amount: Int? = nil, characterId: Int? = nil) {
        self.amount = amount
        self.characterId = characterId
    }

    public enum CodingKeys: String, CodingKey { 
        case amount
        case characterId = "character_id"
    }

}
