//
// GetFwLeaderboardsCharactersVictoryPoints.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Top 100 rankings of pilots by victory points from yesterday, last week and in total */

public struct GetFwLeaderboardsCharactersVictoryPoints: Codable {

    /** Top 100 ranking of pilots active in faction warfare by total victory points. A pilot is considered \&quot;active\&quot; if they have participated in faction warfare in the past 14 days */
    public var activeTotal: [GetFwLeaderboardsCharactersActiveTotalActiveTotal1]
    /** Top 100 ranking of pilots by victory points in the past week */
    public var lastWeek: [GetFwLeaderboardsCharactersLastWeekLastWeek1]
    /** Top 100 ranking of pilots by victory points in the past day */
    public var yesterday: [GetFwLeaderboardsCharactersYesterdayYesterday1]

    public init(activeTotal: [GetFwLeaderboardsCharactersActiveTotalActiveTotal1], lastWeek: [GetFwLeaderboardsCharactersLastWeekLastWeek1], yesterday: [GetFwLeaderboardsCharactersYesterdayYesterday1]) {
        self.activeTotal = activeTotal
        self.lastWeek = lastWeek
        self.yesterday = yesterday
    }

    public enum CodingKeys: String, CodingKey { 
        case activeTotal = "active_total"
        case lastWeek = "last_week"
        case yesterday
    }

}
