//
// GetUniverseStructuresStructureIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetUniverseStructuresStructureIdOk: Codable, Sendable {

    /** The full name of the structure */
    public var name: String
    /** The ID of the corporation who owns this particular structure */
    public var ownerId: Int
    public var position: GetUniverseStructuresStructureIdPosition?
    /** solar_system_id integer */
    public var solarSystemId: Int
    /** type_id integer */
    public var typeId: Int?

    public init(name: String, ownerId: Int, position: GetUniverseStructuresStructureIdPosition? = nil, solarSystemId: Int, typeId: Int? = nil) {
        self.name = name
        self.ownerId = ownerId
        self.position = position
        self.solarSystemId = solarSystemId
        self.typeId = typeId
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case ownerId = "owner_id"
        case position
        case solarSystemId = "solar_system_id"
        case typeId = "type_id"
    }

}
