//
// GetUniverseSystemsSystemIdNotFound.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Not found */

public struct GetUniverseSystemsSystemIdNotFound: Codable {

    /** Not found message */
    public var error: String?

    public init(error: String? = nil) {
        self.error = error
    }


}
