//
// GetUniverseGraphicsGraphicIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetUniverseGraphicsGraphicIdOk: Codable {

    /** collision_file string */
    public var collisionFile: String?
    /** graphic_file string */
    public var graphicFile: String?
    /** graphic_id integer */
    public var graphicId: Int
    /** icon_folder string */
    public var iconFolder: String?
    /** sof_dna string */
    public var sofDna: String?
    /** sof_fation_name string */
    public var sofFationName: String?
    /** sof_hull_name string */
    public var sofHullName: String?
    /** sof_race_name string */
    public var sofRaceName: String?

    public init(collisionFile: String? = nil, graphicFile: String? = nil, graphicId: Int, iconFolder: String? = nil, sofDna: String? = nil, sofFationName: String? = nil, sofHullName: String? = nil, sofRaceName: String? = nil) {
        self.collisionFile = collisionFile
        self.graphicFile = graphicFile
        self.graphicId = graphicId
        self.iconFolder = iconFolder
        self.sofDna = sofDna
        self.sofFationName = sofFationName
        self.sofHullName = sofHullName
        self.sofRaceName = sofRaceName
    }

    public enum CodingKeys: String, CodingKey { 
        case collisionFile = "collision_file"
        case graphicFile = "graphic_file"
        case graphicId = "graphic_id"
        case iconFolder = "icon_folder"
        case sofDna = "sof_dna"
        case sofFationName = "sof_fation_name"
        case sofHullName = "sof_hull_name"
        case sofRaceName = "sof_race_name"
    }

}
