//
// GetUniverseSchematicsSchematicIdNotFound.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Schematic not found */

public struct GetUniverseSchematicsSchematicIdNotFound: Codable {

    /** error message */
    public var error: String?

    public init(error: String? = nil) {
        self.error = error
    }


}
