//
// GetWarsWarIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetWarsWarIdOk: Codable {

    public var aggressor: GetWarsWarIdAggressor
    /** allied corporations or alliances, each object contains either corporation_id or alliance_id */
    public var allies: [GetWarsWarIdAlly]?
    /** Time that the war was declared */
    public var declared: Date
    public var defender: GetWarsWarIdDefender
    /** Time the war ended and shooting was no longer allowed */
    public var finished: Date?
    /** ID of the specified war */
    public var _id: Int
    /** Was the war declared mutual by both parties */
    public var mutual: Bool
    /** Is the war currently open for allies or not */
    public var openForAllies: Bool
    /** Time the war was retracted but both sides could still shoot each other */
    public var retracted: Date?
    /** Time when the war started and both sides could shoot each other */
    public var started: Date?

    public init(aggressor: GetWarsWarIdAggressor, allies: [GetWarsWarIdAlly]? = nil, declared: Date, defender: GetWarsWarIdDefender, finished: Date? = nil, _id: Int, mutual: Bool, openForAllies: Bool, retracted: Date? = nil, started: Date? = nil) {
        self.aggressor = aggressor
        self.allies = allies
        self.declared = declared
        self.defender = defender
        self.finished = finished
        self._id = _id
        self.mutual = mutual
        self.openForAllies = openForAllies
        self.retracted = retracted
        self.started = started
    }

    public enum CodingKeys: String, CodingKey { 
        case aggressor
        case allies
        case declared
        case defender
        case finished
        case _id = "id"
        case mutual
        case openForAllies = "open_for_allies"
        case retracted
        case started
    }

}
