//
// GetWarsWarIdAlly.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** ally object */

public struct GetWarsWarIdAlly: Codable {

    /** Alliance ID if and only if this ally is an alliance */
    public var allianceId: Int?
    /** Corporation ID if and only if this ally is a corporation */
    public var corporationId: Int?

    public init(allianceId: Int? = nil, corporationId: Int? = nil) {
        self.allianceId = allianceId
        self.corporationId = corporationId
    }

    public enum CodingKeys: String, CodingKey { 
        case allianceId = "alliance_id"
        case corporationId = "corporation_id"
    }

}
