//
// PostUiOpenwindowNewmailNewMail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** new_mail object */

public struct PostUiOpenwindowNewmailNewMail: Codable {

    /** body string */
    public var body: String
    /** recipients array */
    public var recipients: [Int]
    /** subject string */
    public var subject: String
    /** to_corp_or_alliance_id integer */
    public var toCorpOrAllianceId: Int?
    /** Corporations, alliances and mailing lists are all types of mailing groups. You may only send to one mailing group, at a time, so you may fill out either this field or the to_corp_or_alliance_ids field */
    public var toMailingListId: Int?

    public init(body: String, recipients: [Int], subject: String, toCorpOrAllianceId: Int? = nil, toMailingListId: Int? = nil) {
        self.body = body
        self.recipients = recipients
        self.subject = subject
        self.toCorpOrAllianceId = toCorpOrAllianceId
        self.toMailingListId = toMailingListId
    }

    public enum CodingKeys: String, CodingKey { 
        case body
        case recipients
        case subject
        case toCorpOrAllianceId = "to_corp_or_alliance_id"
        case toMailingListId = "to_mailing_list_id"
    }

}
