//
// PostCharactersAffiliation200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct PostCharactersAffiliation200Ok: Codable {

    /** The character&#x27;s alliance ID, if their corporation is in an alliance */
    public var allianceId: Int?
    /** The character&#x27;s ID */
    public var characterId: Int
    /** The character&#x27;s corporation ID */
    public var corporationId: Int
    /** The character&#x27;s faction ID, if their corporation is in a faction */
    public var factionId: Int?

    public init(allianceId: Int? = nil, characterId: Int, corporationId: Int, factionId: Int? = nil) {
        self.allianceId = allianceId
        self.characterId = characterId
        self.corporationId = corporationId
        self.factionId = factionId
    }

    public enum CodingKeys: String, CodingKey { 
        case allianceId = "alliance_id"
        case characterId = "character_id"
        case corporationId = "corporation_id"
        case factionId = "faction_id"
    }

}
