//
// PostCharactersCharacterIdFittingsFitting.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** fitting object */

public struct PostCharactersCharacterIdFittingsFitting: Codable {

    /** description string */
    public var _description: String
    /** items array */
    public var items: [PostCharactersCharacterIdFittingsItem]
    /** name string */
    public var name: String
    /** ship_type_id integer */
    public var shipTypeId: Int

    public init(_description: String, items: [PostCharactersCharacterIdFittingsItem], name: String, shipTypeId: Int) {
        self._description = _description
        self.items = items
        self.name = name
        self.shipTypeId = shipTypeId
    }

    public enum CodingKeys: String, CodingKey { 
        case _description = "description"
        case items
        case name
        case shipTypeId = "ship_type_id"
    }

}
