//
// PostCharactersCharacterIdMailRecipient.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** recipient object */

public struct PostCharactersCharacterIdMailRecipient: Codable {

    public enum RecipientType: String, Codable { 
        case alliance = "alliance"
        case character = "character"
        case corporation = "corporation"
        case mailingList = "mailing_list"
    }
    /** recipient_id integer */
    public var recipientId: Int
    /** recipient_type string */
    public var recipientType: RecipientType

    public init(recipientId: Int, recipientType: RecipientType) {
        self.recipientId = recipientId
        self.recipientType = recipientType
    }

    public enum CodingKeys: String, CodingKey { 
        case recipientId = "recipient_id"
        case recipientType = "recipient_type"
    }

}
