//
// Unauthorized.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Unauthorized model */

public struct Unauthorized: Codable {

    /** Unauthorized message */
    public var error: String

    public init(error: String) {
        self.error = error
    }


}
