//
// GetCharactersCharacterIdPortraitNotFound.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** No image server for this datasource */

public struct GetCharactersCharacterIdPortraitNotFound: Codable {

    /** error message */
    public var error: String?

    public init(error: String? = nil) {
        self.error = error
    }


}
