//
// GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** factory_details object */

public struct GetCharactersCharacterIdPlanetsPlanetIdFactoryDetails: Codable {

    /** schematic_id integer */
    public var schematicId: Int

    public init(schematicId: Int) {
        self.schematicId = schematicId
    }

    public enum CodingKeys: String, CodingKey { 
        case schematicId = "schematic_id"
    }

}
