//
// GetCharactersCharacterIdClonesHomeLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** home_location object */

public struct GetCharactersCharacterIdClonesHomeLocation: Codable {

    public enum LocationType: String, Codable { 
        case station = "station"
        case structure = "structure"
    }
    /** location_id integer */
    public var locationId: Int64?
    /** location_type string */
    public var locationType: LocationType?

    public init(locationId: Int64? = nil, locationType: LocationType? = nil) {
        self.locationId = locationId
        self.locationType = locationType
    }

    public enum CodingKeys: String, CodingKey { 
        case locationId = "location_id"
        case locationType = "location_type"
    }

}
