//
// GetCharactersCharacterIdPlanets200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCharactersCharacterIdPlanets200Ok: Codable {

    public enum PlanetType: String, Codable { 
        case temperate = "temperate"
        case barren = "barren"
        case oceanic = "oceanic"
        case ice = "ice"
        case gas = "gas"
        case lava = "lava"
        case storm = "storm"
        case plasma = "plasma"
    }
    /** last_update string */
    public var lastUpdate: Date
    /** num_pins integer */
    public var numPins: Int
    /** owner_id integer */
    public var ownerId: Int
    /** planet_id integer */
    public var planetId: Int
    /** planet_type string */
    public var planetType: PlanetType
    /** solar_system_id integer */
    public var solarSystemId: Int
    /** upgrade_level integer */
    public var upgradeLevel: Int

    public init(lastUpdate: Date, numPins: Int, ownerId: Int, planetId: Int, planetType: PlanetType, solarSystemId: Int, upgradeLevel: Int) {
        self.lastUpdate = lastUpdate
        self.numPins = numPins
        self.ownerId = ownerId
        self.planetId = planetId
        self.planetType = planetType
        self.solarSystemId = solarSystemId
        self.upgradeLevel = upgradeLevel
    }

    public enum CodingKeys: String, CodingKey { 
        case lastUpdate = "last_update"
        case numPins = "num_pins"
        case ownerId = "owner_id"
        case planetId = "planet_id"
        case planetType = "planet_type"
        case solarSystemId = "solar_system_id"
        case upgradeLevel = "upgrade_level"
    }

}
