//
// GetCharactersCharacterIdAttributesOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCharactersCharacterIdAttributesOk: Codable {

    /** Neural remapping cooldown after a character uses remap accrued over time */
    public var accruedRemapCooldownDate: Date?
    /** Number of available bonus character neural remaps */
    public var bonusRemaps: Int?
    /** charisma integer */
    public var charisma: Int
    /** intelligence integer */
    public var intelligence: Int
    /** Datetime of last neural remap, including usage of bonus remaps */
    public var lastRemapDate: Date?
    /** memory integer */
    public var memory: Int
    /** perception integer */
    public var perception: Int
    /** willpower integer */
    public var willpower: Int

    public init(accruedRemapCooldownDate: Date? = nil, bonusRemaps: Int? = nil, charisma: Int, intelligence: Int, lastRemapDate: Date? = nil, memory: Int, perception: Int, willpower: Int) {
        self.accruedRemapCooldownDate = accruedRemapCooldownDate
        self.bonusRemaps = bonusRemaps
        self.charisma = charisma
        self.intelligence = intelligence
        self.lastRemapDate = lastRemapDate
        self.memory = memory
        self.perception = perception
        self.willpower = willpower
    }

    public enum CodingKeys: String, CodingKey { 
        case accruedRemapCooldownDate = "accrued_remap_cooldown_date"
        case bonusRemaps = "bonus_remaps"
        case charisma
        case intelligence
        case lastRemapDate = "last_remap_date"
        case memory
        case perception
        case willpower
    }

}
