//
// GetCharactersCharacterIdClonesOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetCharactersCharacterIdClonesOk: Codable {

    public var homeLocation: GetCharactersCharacterIdClonesHomeLocation?
    /** jump_clones array */
    public var jumpClones: [GetCharactersCharacterIdClonesJumpClone]
    /** last_clone_jump_date string */
    public var lastCloneJumpDate: Date?
    /** last_station_change_date string */
    public var lastStationChangeDate: Date?

    public init(homeLocation: GetCharactersCharacterIdClonesHomeLocation? = nil, jumpClones: [GetCharactersCharacterIdClonesJumpClone], lastCloneJumpDate: Date? = nil, lastStationChangeDate: Date? = nil) {
        self.homeLocation = homeLocation
        self.jumpClones = jumpClones
        self.lastCloneJumpDate = lastCloneJumpDate
        self.lastStationChangeDate = lastStationChangeDate
    }

    public enum CodingKeys: String, CodingKey { 
        case homeLocation = "home_location"
        case jumpClones = "jump_clones"
        case lastCloneJumpDate = "last_clone_jump_date"
        case lastStationChangeDate = "last_station_change_date"
    }

}
