//
// GetInsurancePricesLevel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** level object */

public struct GetInsurancePricesLevel: Codable {

    /** cost number */
    public var cost: Float
    /** Localized insurance level */
    public var name: String
    /** payout number */
    public var payout: Float

    public init(cost: Float, name: String, payout: Float) {
        self.cost = cost
        self.name = name
        self.payout = payout
    }


}
