//
// GetKillmailsKillmailIdKillmailHashVictim.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** victim object */

public struct GetKillmailsKillmailIdKillmailHashVictim: Codable {

    /** alliance_id integer */
    public var allianceId: Int?
    /** character_id integer */
    public var characterId: Int?
    /** corporation_id integer */
    public var corporationId: Int?
    /** How much total damage was taken by the victim  */
    public var damageTaken: Int
    /** faction_id integer */
    public var factionId: Int?
    /** items array */
    public var items: [GetKillmailsKillmailIdKillmailHashItem]?
    public var position: GetKillmailsKillmailIdKillmailHashPosition?
    /** The ship that the victim was piloting and was destroyed  */
    public var shipTypeId: Int

    public init(allianceId: Int? = nil, characterId: Int? = nil, corporationId: Int? = nil, damageTaken: Int, factionId: Int? = nil, items: [GetKillmailsKillmailIdKillmailHashItem]? = nil, position: GetKillmailsKillmailIdKillmailHashPosition? = nil, shipTypeId: Int) {
        self.allianceId = allianceId
        self.characterId = characterId
        self.corporationId = corporationId
        self.damageTaken = damageTaken
        self.factionId = factionId
        self.items = items
        self.position = position
        self.shipTypeId = shipTypeId
    }

    public enum CodingKeys: String, CodingKey { 
        case allianceId = "alliance_id"
        case characterId = "character_id"
        case corporationId = "corporation_id"
        case damageTaken = "damage_taken"
        case factionId = "faction_id"
        case items
        case position
        case shipTypeId = "ship_type_id"
    }

}
