//
// GetLoyaltyStoresCorporationIdOffers200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetLoyaltyStoresCorporationIdOffers200Ok: Codable {

    /** Analysis kredit cost */
    public var akCost: Int?
    /** isk_cost integer */
    public var iskCost: Int64
    /** lp_cost integer */
    public var lpCost: Int
    /** offer_id integer */
    public var offerId: Int
    /** quantity integer */
    public var quantity: Int
    /** required_items array */
    public var requiredItems: [GetLoyaltyStoresCorporationIdOffersRequiredItem]
    /** type_id integer */
    public var typeId: Int

    public init(akCost: Int? = nil, iskCost: Int64, lpCost: Int, offerId: Int, quantity: Int, requiredItems: [GetLoyaltyStoresCorporationIdOffersRequiredItem], typeId: Int) {
        self.akCost = akCost
        self.iskCost = iskCost
        self.lpCost = lpCost
        self.offerId = offerId
        self.quantity = quantity
        self.requiredItems = requiredItems
        self.typeId = typeId
    }

    public enum CodingKeys: String, CodingKey { 
        case akCost = "ak_cost"
        case iskCost = "isk_cost"
        case lpCost = "lp_cost"
        case offerId = "offer_id"
        case quantity
        case requiredItems = "required_items"
        case typeId = "type_id"
    }

}
