//
// GetSovereigntyMap200Ok.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetSovereigntyMap200Ok: Codable {

    /** alliance_id integer */
    public var allianceId: Int?
    /** corporation_id integer */
    public var corporationId: Int?
    /** faction_id integer */
    public var factionId: Int?
    /** system_id integer */
    public var systemId: Int

    public init(allianceId: Int? = nil, corporationId: Int? = nil, factionId: Int? = nil, systemId: Int) {
        self.allianceId = allianceId
        self.corporationId = corporationId
        self.factionId = factionId
        self.systemId = systemId
    }

    public enum CodingKeys: String, CodingKey { 
        case allianceId = "alliance_id"
        case corporationId = "corporation_id"
        case factionId = "faction_id"
        case systemId = "system_id"
    }

}
