//
// GetStatusOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetStatusOk: Codable {

    /** Current online player count */
    public var players: Int
    /** Running version as string */
    public var serverVersion: String
    /** Server start timestamp */
    public var startTime: Date
    /** If the server is in VIP mode */
    public var vip: Bool?

    public init(players: Int, serverVersion: String, startTime: Date, vip: Bool? = nil) {
        self.players = players
        self.serverVersion = serverVersion
        self.startTime = startTime
        self.vip = vip
    }

    public enum CodingKeys: String, CodingKey { 
        case players
        case serverVersion = "server_version"
        case startTime = "start_time"
        case vip
    }

}
