//
// GetUniverseCategoriesCategoryIdOk.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** 200 ok object */

public struct GetUniverseCategoriesCategoryIdOk: Codable {

    /** category_id integer */
    public var categoryId: Int
    /** groups array */
    public var groups: [Int]
    /** name string */
    public var name: String
    /** published boolean */
    public var published: Bool

    public init(categoryId: Int, groups: [Int], name: String, published: Bool) {
        self.categoryId = categoryId
        self.groups = groups
        self.name = name
        self.published = published
    }

    public enum CodingKeys: String, CodingKey { 
        case categoryId = "category_id"
        case groups
        case name
        case published
    }

}
