//
// GetWarsWarIdDefender.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The defending corporation or alliance that declared this war, only contains either corporation_id or alliance_id */

public struct GetWarsWarIdDefender: Codable {

    /** Alliance ID if and only if the defender is an alliance */
    public var allianceId: Int?
    /** Corporation ID if and only if the defender is a corporation */
    public var corporationId: Int?
    /** ISK value of ships the defender has killed */
    public var iskDestroyed: Float
    /** The number of ships the defender has killed */
    public var shipsKilled: Int

    public init(allianceId: Int? = nil, corporationId: Int? = nil, iskDestroyed: Float, shipsKilled: Int) {
        self.allianceId = allianceId
        self.corporationId = corporationId
        self.iskDestroyed = iskDestroyed
        self.shipsKilled = shipsKilled
    }

    public enum CodingKeys: String, CodingKey { 
        case allianceId = "alliance_id"
        case corporationId = "corporation_id"
        case iskDestroyed = "isk_destroyed"
        case shipsKilled = "ships_killed"
    }

}
