//
// PostUiOpenwindowNewmailUnprocessableEntity.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Unprocessable entity */

public struct PostUiOpenwindowNewmailUnprocessableEntity: Codable {

    /** Unprocessable entity message */
    public var error: String?

    public init(error: String? = nil) {
        self.error = error
    }


}
