//
// PutFleetsFleetIdWingsWingIdNaming.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** naming object */

public struct PutFleetsFleetIdWingsWingIdNaming: Codable {

    /** name string */
    public var name: String

    public init(name: String) {
        self.name = name
    }


}
